### ISSUE TITLE
Getting error [!] (plugin import-assertions) TypeError: self.load is not a function

### ISSUE THREAD

**Issue by khashashin** [swiing/rollup-plugin-import-assertions#3]
Installing rollup cli and executing `rollup -c rollup.config.js` works without any errors but when I run this using `npm run build` then I get following error:

```
╰─ npm run build                                                                                                                                                 ─╯ 

> gramps-js@0.13.2 build
> rimraf dist && rollup -c rollup.config.js


./index.html → dist...
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
(node:21616) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at C:\Users\khash\Developme
nt\gramps-project\Gramps.js\node_modules\tslib\package.json.                                                                                                        Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
[!] (plugin import-assertions) TypeError: self.load is not a function
src\lang\index.js
TypeError: self.load is not a function
    at C:\Users\khash\Development\gramps-project\Gramps.js\node_modules\rollup-plugin-import-assertions\src\index.js:143:16
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at Object.transform (C:\Users\khash\Development\gramps-project\Gramps.js\node_modules\rollup-plugin-import-assertions\src\index.js:126:7)
    at ModuleLoader.addModuleSource (C:\Users\khash\Development\gramps-project\Gramps.js\node_modules\rollup\dist\shared\rollup.js:19708:30)
    at ModuleLoader.fetchModule (C:\Users\khash\Development\gramps-project\Gramps.js\node_modules\rollup\dist\shared\rollup.js:19761:9)
    at async Promise.all (index 0)
    at ModuleLoader.fetchStaticDependencies (C:\Users\khash\Development\gramps-project\Gramps.js\node_modules\rollup\dist\shared\rollup.js:19792:34)
    at async Promise.all (index 0)


```

My `package.json` build command:

```
  "scripts": {
    "lint:eslint": "eslint --ext .js,.html . --ignore-path .gitignore",
    "format:eslint": "eslint --ext .js,.html . --fix --ignore-path .gitignore",
    "lint:prettier": "prettier \"**/*.js\" --check --ignore-path .gitignore",
    "format:prettier": "prettier \"**/*.js\" --write --ignore-path .gitignore",
    "lint": "npm run lint:eslint && npm run lint:prettier",
    "format": "npm run format:eslint && npm run format:prettier",
    "build": "rollup -c rollup.config.js",
    "start": "web-dev-server --app-index index.html --node-resolve --open --watch"
  }
```

And here is my rollup.config.js

```
import merge from 'deepmerge'
import copy from 'rollup-plugin-copy'
import { createSpaConfig } from '@open-wc/building-rollup'
import importAssertions from 'rollup-plugin-import-assertions'
import replace from '@rollup/plugin-replace'

const API_URL = (process.env.API_URL === undefined)
  ? ''
  : process.env.API_URL

const BASE_DIR = (process.env.BASE_DIR === undefined)
  ? ''
  : process.env.BASE_DIR

const baseConfig = createSpaConfig({
  developmentMode: process.env.ROLLUP_WATCH === 'true',
  injectServiceWorker: true,
  workbox: {
    navigateFallbackDenylist: [/^\/api.*/],
    skipWaiting: false,
    clientsClaim: false
  },
  html: {
    transform: [
      (html) =>
        html.replace(
          '<base href="/">',
          `<base href="${BASE_DIR}/">`
        )
    ]
  }
})

export default merge(baseConfig, {
  input: './index.html',
  plugins: [
    copy({
      targets: [
        { src: './leaflet.css', dest: 'dist/' },
        { src: './manifest.json', dest: 'dist/' },
        { src: './images/**/*', dest: 'dist/images' },
        {
          src: 'node_modules/@hpcc-js/wasm/dist/graphvizlib.wasm',
          dest: 'dist/'
        },
        {
          src: 'node_modules/@hpcc-js/wasm/dist/graphvizlib.wasm',
          dest: 'dist/@hpcc-js/wasm'
        },
        {
          src: 'node_modules/@hpcc-js/wasm/dist/index.min.js',
          dest: 'dist/@hpcc-js/wasm'
        }
      ]
    }),
    replace({
      'http://localhost:5555': API_URL,
      BASE_DIR: JSON.stringify(BASE_DIR),
      preventAssignment: true
    }),
    importAssertions()
  ]
})

```

**Comment by swiing** [comment]
Thanks for raising this.

Could you please try again with a rollup version >= 2.60.0?
I expect your local rollup is "old" (`npm run build` fails), while your global rollup is more recent (`rollup -c` works).

I will update the version of the peer dependency to make sure this error does not happen again.

**Comment by khashashin** [comment]
Yes upgrading the rollup in `package.json` to 2.60.2 has fixed the issue

thank you very much!
